// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Category.
const (
	CategoryAI       Category = "AI系"
	CategoryHotTopic Category = "ホットトピック"
	CategoryIT       Category = "IT系"
	CategoryOther    Category = "その他"
	CategorySecurity Category = "セキュリティ"
	CategoryTools    Category = "面白そうなツール・サービス"
	CategoryUI       Category = "UI系"
)

// Valid indicates whether the value is a known member of the Category enum.
func (e Category) Valid() bool {
	switch e {
	case CategoryAI:
		return true
	case CategoryHotTopic:
		return true
	case CategoryIT:
		return true
	case CategoryOther:
		return true
	case CategorySecurity:
		return true
	case CategoryTools:
		return true
	case CategoryUI:
		return true
	default:
		return false
	}
}

// Defines values for ProblemType.
const (
	AboutBlank               ProblemType = "about:blank"
	Problemsforbidden        ProblemType = "/problems/forbidden"
	ProblemsnotFound         ProblemType = "/problems/not-found"
	Problemsunauthorized     ProblemType = "/problems/unauthorized"
	ProblemsupstreamFailed   ProblemType = "/problems/upstream-failed"
	ProblemsvalidationFailed ProblemType = "/problems/validation-failed"
)

// Valid indicates whether the value is a known member of the ProblemType enum.
func (e ProblemType) Valid() bool {
	switch e {
	case AboutBlank:
		return true
	case Problemsforbidden:
		return true
	case ProblemsnotFound:
		return true
	case Problemsunauthorized:
		return true
	case ProblemsupstreamFailed:
		return true
	case ProblemsvalidationFailed:
		return true
	default:
		return false
	}
}

// AdminUser defines model for AdminUser.
type AdminUser struct {
	// Id GitHub 固定 ID。サービス内で管理者を指す識別子
	Id    int64  `json:"id"`
	Login string `json:"login"`
}

// Article defines model for Article.
type Article struct {
	Category Category `json:"category"`

	// Description ページの説明文。取得できた記事だけ持つ
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Title       string             `json:"title"`
	Url         string             `json:"url"`
}

// Category defines model for Category.
type Category string

// CreatedSession defines model for CreatedSession.
type CreatedSession struct {
	ExpiresAt time.Time `json:"expiresAt"`

	// Token 不透明トークン。Cookie に入れて Bearer で転送する
	Token string    `json:"token"`
	User  AdminUser `json:"user"`
}

// Digest defines model for Digest.
type Digest struct {
	EntryDate openapi_types.Date `json:"entryDate"`
	Id        openapi_types.UUID `json:"id"`
	Items     []Article          `json:"items"`
}

// Item defines model for Item.
type Item struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Title     string             `json:"title"`
}

// NewItem defines model for NewItem.
type NewItem struct {
	Title string `json:"title"`
}

// NewSession defines model for NewSession.
type NewSession struct {
	// Code GitHub authorize から戻った code
	Code string `json:"code"`

	// RedirectUri authorize に渡した redirect_uri。token 交換で GitHub が一致を検証する
	RedirectUri string `json:"redirectUri"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail *string `json:"detail,omitempty"`
	Status int     `json:"status"`
	Title  string  `json:"title"`

	// Type エラー種別。クライアントはこれで分岐する。想定外は about:blank
	Type ProblemType `json:"type"`
}

// ProblemType エラー種別。クライアントはこれで分岐する。想定外は about:blank
type ProblemType string

// Session defines model for Session.
type Session struct {
	ExpiresAt time.Time `json:"expiresAt"`
	User      AdminUser `json:"user"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Problem

// Unauthorized defines model for Unauthorized.
type Unauthorized = Problem

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = NewSession

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = NewItem

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateSession GitHub の code を検証し、管理者の session を発行する
	// (POST /auth/sessions)
	CreateSession(c *gin.Context)
	// DeleteCurrentSession Bearer の session を削除する (ログアウト)。存在しなくても 204
	// (DELETE /auth/sessions/current)
	DeleteCurrentSession(c *gin.Context)
	// GetCurrentSession Bearer の session を照合し、管理者を返す
	// (GET /auth/sessions/current)
	GetCurrentSession(c *gin.Context)

	// (GET /digests/latest)
	GetLatestDigest(c *gin.Context)

	// (GET /health)
	Health(c *gin.Context)

	// (GET /items)
	ListItems(c *gin.Context)

	// (POST /items)
	CreateItem(c *gin.Context)

	// (GET /items/{id})
	GetItem(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateSession(c)
}

// DeleteCurrentSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteCurrentSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteCurrentSession(c)
}

// GetCurrentSession operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCurrentSession(c)
}

// GetLatestDigest operation middleware
func (siw *ServerInterfaceWrapper) GetLatestDigest(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLatestDigest(c)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Health(c)
}

// ListItems operation middleware
func (siw *ServerInterfaceWrapper) ListItems(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListItems(c)
}

// CreateItem operation middleware
func (siw *ServerInterfaceWrapper) CreateItem(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateItem(c)
}

// GetItem operation middleware
func (siw *ServerInterfaceWrapper) GetItem(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetItem(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.Health)
	router.GET(options.BaseURL+"/items", wrapper.ListItems)
	router.POST(options.BaseURL+"/items", wrapper.CreateItem)
	router.GET(options.BaseURL+"/items/:id", wrapper.GetItem)
	router.GET(options.BaseURL+"/digests/latest", wrapper.GetLatestDigest)
	router.POST(options.BaseURL+"/auth/sessions", wrapper.CreateSession)
	router.DELETE(options.BaseURL+"/auth/sessions/current", wrapper.DeleteCurrentSession)
	router.GET(options.BaseURL+"/auth/sessions/current", wrapper.GetCurrentSession)
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type CreateSessionRequestObject struct {
	Body *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

type CreateSession201JSONResponse CreatedSession

func (response CreateSession201JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateSession400ApplicationProblemPlusJSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession403ApplicationProblemPlusJSONResponse Problem

func (response CreateSession403ApplicationProblemPlusJSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession502ApplicationProblemPlusJSONResponse Problem

func (response CreateSession502ApplicationProblemPlusJSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCurrentSessionRequestObject struct {
}

type DeleteCurrentSessionResponseObject interface {
	VisitDeleteCurrentSessionResponse(w http.ResponseWriter) error
}

type DeleteCurrentSession204Response struct {
}

func (response DeleteCurrentSession204Response) VisitDeleteCurrentSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCurrentSession401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response DeleteCurrentSession401ApplicationProblemPlusJSONResponse) VisitDeleteCurrentSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentSessionRequestObject struct {
}

type GetCurrentSessionResponseObject interface {
	VisitGetCurrentSessionResponse(w http.ResponseWriter) error
}

type GetCurrentSession200JSONResponse Session

func (response GetCurrentSession200JSONResponse) VisitGetCurrentSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCurrentSession401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetCurrentSession401ApplicationProblemPlusJSONResponse) VisitGetCurrentSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetLatestDigestRequestObject struct {
}

type GetLatestDigestResponseObject interface {
	VisitGetLatestDigestResponse(w http.ResponseWriter) error
}

type GetLatestDigest200JSONResponse Digest

func (response GetLatestDigest200JSONResponse) VisitGetLatestDigestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetLatestDigest404ApplicationProblemPlusJSONResponse Problem

func (response GetLatestDigest404ApplicationProblemPlusJSONResponse) VisitGetLatestDigestResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(w http.ResponseWriter) error
}

type Health200JSONResponse struct {
	Status string `json:"status"`
}

func (response Health200JSONResponse) VisitHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListItemsRequestObject struct {
}

type ListItemsResponseObject interface {
	VisitListItemsResponse(w http.ResponseWriter) error
}

type ListItems200JSONResponse struct {
	Items []Item `json:"items"`
}

func (response ListItems200JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateItemRequestObject struct {
	Body *CreateItemJSONRequestBody
}

type CreateItemResponseObject interface {
	VisitCreateItemResponse(w http.ResponseWriter) error
}

type CreateItem201JSONResponse Item

func (response CreateItem201JSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateItem400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateItem400ApplicationProblemPlusJSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetItemRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetItemResponseObject interface {
	VisitGetItemResponse(w http.ResponseWriter) error
}

type GetItem200JSONResponse Item

func (response GetItem200JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetItem400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetItem400ApplicationProblemPlusJSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetItem404ApplicationProblemPlusJSONResponse Problem

func (response GetItem404ApplicationProblemPlusJSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreateSession GitHub の code を検証し、管理者の session を発行する
	// (POST /auth/sessions)
	CreateSession(ctx context.Context, request CreateSessionRequestObject) (CreateSessionResponseObject, error)
	// DeleteCurrentSession Bearer の session を削除する (ログアウト)。存在しなくても 204
	// (DELETE /auth/sessions/current)
	DeleteCurrentSession(ctx context.Context, request DeleteCurrentSessionRequestObject) (DeleteCurrentSessionResponseObject, error)
	// GetCurrentSession Bearer の session を照合し、管理者を返す
	// (GET /auth/sessions/current)
	GetCurrentSession(ctx context.Context, request GetCurrentSessionRequestObject) (GetCurrentSessionResponseObject, error)

	// (GET /digests/latest)
	GetLatestDigest(ctx context.Context, request GetLatestDigestRequestObject) (GetLatestDigestResponseObject, error)

	// (GET /health)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)

	// (GET /items)
	ListItems(ctx context.Context, request ListItemsRequestObject) (ListItemsResponseObject, error)

	// (POST /items)
	CreateItem(ctx context.Context, request CreateItemRequestObject) (CreateItemResponseObject, error)

	// (GET /items/{id})
	GetItem(ctx context.Context, request GetItemRequestObject) (GetItemResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// CreateSession operation middleware
func (sh *strictHandler) CreateSession(ctx *gin.Context) {
	var request CreateSessionRequestObject

	var body CreateSessionJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSession(ctx, request.(CreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateSessionResponseObject); ok {
		if err := validResponse.VisitCreateSessionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCurrentSession operation middleware
func (sh *strictHandler) DeleteCurrentSession(ctx *gin.Context) {
	var request DeleteCurrentSessionRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCurrentSession(ctx, request.(DeleteCurrentSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCurrentSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeleteCurrentSessionResponseObject); ok {
		if err := validResponse.VisitDeleteCurrentSessionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentSession operation middleware
func (sh *strictHandler) GetCurrentSession(ctx *gin.Context) {
	var request GetCurrentSessionRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentSession(ctx, request.(GetCurrentSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentSession")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetCurrentSessionResponseObject); ok {
		if err := validResponse.VisitGetCurrentSessionResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLatestDigest operation middleware
func (sh *strictHandler) GetLatestDigest(ctx *gin.Context) {
	var request GetLatestDigestRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetLatestDigest(ctx, request.(GetLatestDigestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLatestDigest")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetLatestDigestResponseObject); ok {
		if err := validResponse.VisitGetLatestDigestResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Health operation middleware
func (sh *strictHandler) Health(ctx *gin.Context) {
	var request HealthRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx, request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		if err := validResponse.VisitHealthResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListItems operation middleware
func (sh *strictHandler) ListItems(ctx *gin.Context) {
	var request ListItemsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListItems(ctx, request.(ListItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListItems")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListItemsResponseObject); ok {
		if err := validResponse.VisitListItemsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateItem operation middleware
func (sh *strictHandler) CreateItem(ctx *gin.Context) {
	var request CreateItemRequestObject

	var body CreateItemJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateItem(ctx, request.(CreateItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateItemResponseObject); ok {
		if err := validResponse.VisitCreateItemResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetItem operation middleware
func (sh *strictHandler) GetItem(ctx *gin.Context, id openapi_types.UUID) {
	var request GetItemRequestObject

	request.Id = id

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetItem(ctx, request.(GetItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetItemResponseObject); ok {
		if err := validResponse.VisitGetItemResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFdvUxTJGf8qU5288CqDu6jJi32HWDmpWHoV5ZVFpYadBvrcnZnr6TESa6u2exS5kzvInaeAXnkoCoGw",
	"5OIl5YHRD/Mwu8u3SHX3zO4sO8sWnmAVVWz/e/785vnze26jolv2XAc7zEeF24hi33MdH6vFecv+M/4i",
	"wD6Tq6LrMOyon5bnlUjRYsR1ch51x0u4/LvPfdeRZ35xCpct+eu3FE+gAvpNrq0ip0/93Gf6FapUKiay",
	"sV+kxJPiUEFqNRK1FRONOlbAplxK/obtkzSjQ688jt9IkUN2mTijPqZy4VHXw5QRjRlRRnaK+pSwi8G4",
	"ET3eiWrLxsgFqAoQ/4HwDYTfgfglmrkLfK1RW2kszDSrd0F8W5+7B3ypubUYzb6IthaQiSZcWrYYKiDi",
	"sD+cQyZi0x7WSzyJqQSq5E4S5Xp85DNKnEllOsVfBIRK/K5LA5O7Yy0x7vjnuKjgHqKMFEu427GixfCk",
	"S6f7QTqc3DuI6EFUIFyWEIjXwGvNjX/WF7+pP7wHVRHNP4zePgK+Bvxr4E+b64t7O/eB/wj87/U5Dny1",
	"7X3iohnD3kIpCJSbXdcYYdq3rpOAljolUNItIAvKFi6JdC0rC9vhFITYCcpSBohdEFsQvoBwA8IZEM+R",
	"iSB8DGEI4az6eyB/i21kopFrjVe7yESjI/r/UPx//4dnjaX/Af8B+AzwDQjvqODahHA3HWhSsrxT29t9",
	"mDIw9s5EtwakVQM3LepYZfnVr7dMvoqLASVMeplsXXTZNdcjxdTWyLXUYnQktRhKL665bslPra+wKUzR",
	"mESIYoth+yr2/ThmrFLpygQqXD886JIHFfNg2DL3Bs4Ivr3XX+9X5+uL3yiE34DYhvAVVMWw694g2AC+",
	"Gd19AWIO+EvjPLYopgbwtebus/0qB74E4n7f6NCau+NA+nmBTMZVtdNa7DA6fcFiuCMWbbnx/kFPGC7r",
	"2pT8OAzKpABUWpIsSq3p7OBv25uoyYr7EYbLGQVFf+sh1uXrACNlfAxZnuVBkrNta7I8uIz/mu1ES1XZ",
	"unUJO5NsChXO5PMmKhMnWQ/2jRQlpIfeVC4cwM+1cc9e0+pdBvD7IL6sz+4Cfw78qaGemUezV5prE4qL",
	"bJSSbp1pZZv11yvAH0lNyZu/BJRAVah8MPZ2Vuvzj4GvGbGlwOf2Xleb936WfW/1SXP9TSu/jlSMY7/S",
	"hmYhmnT8LjhtzCxSyuwNPrNY4KeOUl23d0fRG11dT6xD+A8I3zTWa9HsC0UFtuWOWAXxTBahcBb4NvDv",
	"VPVZi2Znon8vaEigKurhq6i2HK0+BL5tWONuwArjJcu5oXJRd5TO3YQY+bmbVonYiiwNTFikhO2OU8dl",
	"AxNu4HTuBmkSlD6YcOk4sW3sdF73fEaxVU4UjPWNfHnaTsIY6Kzv1jMN8C2PUOwfpYwEMXM7tAy2KN5B",
	"m9VrM6W321wZM3HDvCrlaUvHVR8ZCmSOxQRVPtLbbTunGPM0ISXOhJsqMkj64xtDn8leehNTjQfKnx48",
	"nZduuR52LI+gAjp7On/6LDKRZ7EppTonP2PO1xiqHc/V/UdCqYJixEaFuP8mWGu/sc/Ou/b0Idz7aJw7",
	"VdMqndgyGmC1kZpBzuQHP5jmA+wig/THN1rVKs5EXovePWlsPQC+qYloY/6tTE9xX+J+Lp/vpbnlSi41",
	"S6knZ09ylmmu/xTNbwP/XjMa4HckS+R3WjVYPAOxCeJlXH8kx3kL/KksMuNW8QZ2bAN4Lbm+X31eX9gB",
	"Pld/stFc34pqy9Kn3+fPnKRPrfaxDry2X13ee7cC4W7ynWpJK9mMVn+qf//IOCX7g2w2jTsr0Ve/AN+I",
	"fvw5WpgFIaKFTRDVT3TaBuWyJRl6W37N0E/b7ekRVHl7XOM1I04seaextNNcmYtbmJTYmXq5YkBpDI+N",
	"S1gzvc4kvKD2h/XFdC52pMW57t5y2TWGY/RVjA32D8vuKTch+pJypyvW9bHKWBqfFivucD/68qv9pVXt",
	"vnEKwi0Q/1LR9RLC2U/kdLe1GD1ZVwxhA/i8jEYhDOlOxUSTOKMmfYpZPyzyH6xEHFIbrvzpo6HauLsm",
	"Q/VA4Ilvm+8eAF/SYWarkcLPlSwWjxa90LykbsQjyDFiGWs4BMpzJ1kwLrvM+KNkOMYpbZmsBsagsbf7",
	"XxBCF0RZBBSaU9gq6T6dieJFffwrweskMl0sswdn6kmSsnHW/rRGv0x3LhGfjagbH9Sjow2easDqO3X2",
	"GDJ7+W4eSnSUymNjOdqhk6U4bZ2ZxOa96EoqgnK3iV05rLbEiHoWtcqYYeqrikekCZKMIhM5lmK9avju",
	"xMVM+dhnxpdF89jqVi8Mk6r1Hmzv4xQ69ekqlf8HAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
