// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token_hash, user_id, expires_at) VALUES ($1, $2, $3) RETURNING id, token_hash, user_id, created_at, expires_at
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    int64
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = $1
`

// 0 行でもエラーにしない (ログアウトの冪等性)
func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT sessions.id, sessions.token_hash, sessions.user_id, sessions.created_at, sessions.expires_at, users.login FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE token_hash = $1 AND expires_at > now()
`

type GetSessionByTokenHashRow struct {
	ID        uuid.UUID
	TokenHash []byte
	UserID    int64
	CreatedAt time.Time
	ExpiresAt time.Time
	Login     string
}

// 期限切れの行が残っていても無効 (specs/003 Assumptions)
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Login,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, login) VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET login = EXCLUDED.login, updated_at = now()
RETURNING id, login, created_at, updated_at
`

type UpsertUserParams struct {
	ID    int64
	Login string
}

// 初回は作成、2 回目以降は login の最新値と最終ログインを更新する
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.ID, arg.Login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
