// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digests.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getLatestDigest = `-- name: GetLatestDigest :one
SELECT id, entry_date, created_at FROM digests ORDER BY entry_date DESC, created_at DESC LIMIT 1
`

// 同じ日付が複数あれば後に登録したものを採用する (specs/002 Edge Cases)
func (q *Queries) GetLatestDigest(ctx context.Context) (Digest, error) {
	row := q.db.QueryRow(ctx, getLatestDigest)
	var i Digest
	err := row.Scan(&i.ID, &i.EntryDate, &i.CreatedAt)
	return i, err
}

const listArticlesByDigest = `-- name: ListArticlesByDigest :many
SELECT id, digest_id, position, category, title, url, description FROM articles WHERE digest_id = $1 ORDER BY position
`

// position = 登録時のカテゴリ順・カテゴリ内順 (specs/002 FR-004)
func (q *Queries) ListArticlesByDigest(ctx context.Context, digestID uuid.UUID) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticlesByDigest, digestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.DigestID,
			&i.Position,
			&i.Category,
			&i.Title,
			&i.Url,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
