// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Article struct {
	ID          uuid.UUID
	DigestID    uuid.UUID
	Position    int32
	Category    string
	Title       string
	Url         string
	Description *string
}

type Digest struct {
	ID        uuid.UUID
	EntryDate time.Time
	CreatedAt time.Time
}

type Item struct {
	ID        uuid.UUID
	Title     string
	CreatedAt time.Time
}

type Session struct {
	ID        uuid.UUID
	TokenHash []byte
	UserID    int64
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID        int64
	Login     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
